### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-PHAL-plugin-respeaker-2mic#1]
```
Successfully installed ovos-PHAL-plugin-respeaker-2mic-0.0.1
2023-11-25 23:30:14.224 - PHAL - ovos_PHAL.service:on_started:25 - INFO - PHAL is started
2023-11-25 23:30:14.257 - PHAL - ovos_bus_client.session:from_message:447 - WARNING - No session context in message:connected
2023-11-25 23:30:14.519 - PHAL - ovos_PHAL.service:load_plugins:85 - ERROR - failed to load PHAL plugin: ovos-PHAL-plugin-respeaker-2mic
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL/service.py", line 82, in load_plugins
    self.drivers[name] = plug(bus=self.bus, config=config)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 18, in __init__
    self.button.on_press(self.handle_button_press)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/drivers/button.py", line 97, in on_press
    GPIO.add_event_detect(
RuntimeError: Failed to add edge detection
2023-11-25 23:30:14.534 - PHAL - ovos_PHAL.service:load_plugins:83 - INFO - PHAL plugin loaded: ovos-phal-plugin-ipgeo
2023-11-25 23:30:14.651 - PHAL - ovos_PHAL.service:load_plugins:83 - INFO - PHAL plugin loaded: ovos-PHAL-plugin-alsa
2023-11-25 23:30:14.659 - PHAL - ovos_PHAL.service:load_plugins:83 - INFO - PHAL plugin loaded: ovos-PHAL-plugin-system
2023-11-25 23:30:14.661 - PHAL - ovos_PHAL.service:on_ready:9 - INFO - PHAL is ready.
exception calling callback for <Future at 0x7f8205db90 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 38, in on_record_begin
    self.led.listen()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
exception calling callback for <Future at 0x7f82042390 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 41, in on_record_end
    self.on_reset(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 53, in on_reset
    self.led.off()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
exception calling callback for <Future at 0x7f8206a650 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 44, in on_audio_output_start
    self.led.speak()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
exception calling callback for <Future at 0x7f82043d50 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 47, in on_audio_output_end
    self.on_reset(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 53, in on_reset
    self.led.off()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
exception calling callback for <Future at 0x7f821df2d0 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 38, in on_record_begin
    self.led.listen()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
exception calling callback for <Future at 0x7f8205de50 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 41, in on_record_end
    self.on_reset(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 53, in on_reset
    self.led.off()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
exception calling callback for <Future at 0x7f82068e90 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/phal.py", line 356, in _on_mouth_think
    self.on_think(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 50, in on_think
    self.led.think()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
exception calling callback for <Future at 0x7f8206bdd0 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 44, in on_audio_output_start
    self.led.speak()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
exception calling callback for <Future at 0x7f8205e910 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 47, in on_audio_output_end
    self.on_reset(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_respeaker_2mic/__init__.py", line 53, in on_reset
    self.led.off()
    ^^^^^^^^
AttributeError: 'Respeaker2MicControlPlugin' object has no attribute 'led'
```

**Comment by builderjer** [comment]
I believe this is specific to kernel >=6.6

It was working with 6.1
